apps/orders/urls.py
from django.conf.urls import url
from .views import (
    OrderListView,
    OrderDetailView
)

urlpatterns = [
    url(r'^$', OrderListView.as_view(), name='list'),
    url(r'^(?P<order_id>[0-9A-Za-z]+)/$', OrderDetailView.as_view(), name='detail'),
]

eCommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.views.generic import TemplateView, RedirectView

from accounts.views import LoginView, RegisterView, GuestRegisterView
from carts.views import cart_detail_api_view
from billing.views import payment_method_view, payment_method_createview
from marketing.views import MarketingPreferenceUpdateView, MailchimpWebhookView
from addresses.views import (
    AddressCreateView,
    AddressListView,
    checkout_address_create_view,
    checkout_address_reuse_view,
    AddressUpdateView,
)
from orders.views import LibraryView
from .views import home_page, about_page, contact_page

urlpatterns = [
    url(r'^$', home_page, name='home'),
    url(r'^about/$', about_page, name='about'),
    url(r'^contact/$', contact_page, name='contact'),
    # url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^accounts/$', RedirectView.as_view(url='/account')),
    url(r'^account/', include("accounts.urls", namespace='account')),
    url(r'^accounts/', include("accounts.passwords.urls")),
    url(r'^address/$', RedirectView.as_view(url='/addresses')),
    url(r'^addresses/$', AddressListView.as_view(), name='addresses'),
    url(r'^addresses/create/$', AddressCreateView.as_view(), name='address-create'),
    url(r'^addresses/(?P<pk>\d+)/$', AddressUpdateView.as_view(), name='address-update'),
    url(r'^checkout/address/create/$', checkout_address_create_view, name='checkout_address_create'),
    url(r'^checkout/address/reuse/$', checkout_address_reuse_view, name='checkout_address_reuse'),
    url(r'^register/guest/$', GuestRegisterView.as_view(), name='guest_register'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^api/cart/$', cart_detail_api_view, name='api-cart'),
    url(r'^cart/', include("carts.urls", namespace='cart')),
    url(r'^billing/payment-method/$', payment_method_view, name='billing-payment-method'),
    url(r'^billing/payment-method/create/$', payment_method_createview, name='billing-payment-method-endpoint'),
    url(r'^register/$', RegisterView.as_view(), name='register'),
    url(r'^bootstrap/$', TemplateView.as_view(template_name='example.html')),
    url(r'^library/$', LibraryView.as_view(), name='library'),
    url(r'^orders/', include("orders.urls", namespace='orders')),
    url(r'^products/', include("products.urls", namespace='products')),
    url(r'^search/', include("search.urls", namespace='search')),

    url(r'^settings/$', RedirectView.as_view(url='/account')),
    url(r'^settings/email/$', MarketingPreferenceUpdateView.as_view(), name='marketing-pref'),
    url(r'^webhooks/mailchimp/$', MailchimpWebhookView.as_view(), name='webhooks-mailchimp'),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Base Template</title>
    {% include 'base/css.html' %}
    {% block base_head %}{% endblock %}
</head>
<body>
{% include 'base/navbar.html' with brand_name='eCommerce' %}
<div class='container'>
    {% if messages %}
        <div class="alert alert-success messages">
            {% for message in messages %}
                <span{% if message.tags %} class="{{ message.tags }}"{% endif %}>
              {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
                    {{ message }}<br/>
          </span>
            {% endfor %}
        </div>
    {% endif %}
    {% block content %}{% endblock %}
</div>

{% include 'base/js.html' %}
{% block javascript %}

{% endblock %}
</body>
</html>

templates/css.html
{% load static %}
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
<link rel='stylesheet' href='{% static "css/main.css" %}'>

templates/example.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
</head>
<body>


<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class='container'>
        <a class="navbar-brand" href="#">
            <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30"
                 class="d-inline-block align-top" alt="">
            Bootstrap
        </a>
        <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarCollapseLinks'
                aria-expanded='false' aria-label='Toggle Navigation'>
            <span class='navbar-toggler-icon'></span>
        </button>


        <div class='collapse navbar-collapse' id='navbarCollapseLinks'>
            <ul class='navbar-nav'>
                <li class='nav-item'>
                    <a href='#' class='nav-link'>Home</a>
                </li>
                <li class='nav-item'>
                    <a href='#' class='nav-link'>About</a>
                </li>
                <li class='nav-item'>
                    <a href='#' class='nav-link'>Products</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>

            </ul>


            <form class="form-inline ml-auto">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="clo-12">
            <div class="alert alert-secondary" role="alert">nav</div>
        </div>
    </div>
    <div class="row mb-3"> <!-- mb-3 外边距-->
        {#     不同设备不同的宽度#}
        <div class='col-12 col-sm-12 col-md-6 col-lg-4 ml-auto'>
            <input type='text' class='form-control' placeholder="Search">
        </div>
    </div>
</div>
<div class="row">
    <div class='col-11 mx-auto  col-lg-2 order-12'>
        <div class="alert alert-primary" role="alert"> 1111Bottom Content Item</div>
    </div>
</div>
<div class='col-11 col-lg-8 mx-auto order-6'>
    <div class="alert alert-primary" role="alert" style='min-height: 800px;'>
        Middle

        <div class="row">
            <div class="col-8">
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-4'>
                <div class="alert alert-secondary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
        </div>

        <div class="row">
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
            <div class='col-1'>
                <div class="alert alert-primary" role="alert">
                    This is a primary alert—check it out!
                </div>
            </div>
        </div>
    </div>
</div>


<div class='col-12 col-lg-2 order-1'>
    <div class="alert alert-secondary" role="alert"></div>
</div>


<div class='container'>
    <div class='row'>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
    </div>
</div>

<div class='container-fluid'>
    <div class='row'>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-primary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>
        <div class='col-1'>
            <div class="alert alert-secondary" role="alert">
                This is a primary alert—check it out!
            </div>
        </div>

    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</body>
</html>

templates/home_page.html
{% extends "base.html" %}
{% load static %}

<title>Home Page Template</title>

{% block base_head %}
    <link rel='stylesheet' href='{% static "css/main.css" %}'>
{% endblock %}

{% block content %}
    <div class='text-center'>
        <h1>{{ title }}</h1>
        <h1>Hello, world we're working!</h1>
    </div>

    <div class='row'>
        <div class='col'>
            <img src="{% static 'img/beach.jpg' %}" class='img-fluid'/>
            <p>{{ content }}</p>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <div class='row'>
            <div class='col'>
                <h1>Premium</h1>
                {{ premium_content }}
            </div>
        </div>
    {% endif %}


{% endblock %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link rel='stylesheet' href='{% static "css/main.css" %}'>
</head>
<body>
<div class='text-center'>
    <h1>{{ title }}</h1>
    <h1>Hello, world we're working!</h1>
</div>
<div class='container'>
    <div class='row'>
        <div class='col'>
            <img src="{% static 'img/beach.jpg' %}" class='img-fluid'/>
            <p>{{ content }}</p>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <div class='row'>
            <div class='col'>
                <h1>Premium</h1>
                {{ premium_content }}
            </div>
        </div>
    {% endif %}
</div>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
</body>
</html>

templates/navbar.html
{% url 'home' as home_url %}
{% url 'contact' as contact_url %}
{% url 'products:list' as product_list_url %}
{% url 'login' as login_url %}
{% url 'register' as register_url %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
    <div class='container'>
        <a class="navbar-brand" href="{{ home_url }}">
            <img src="http://getbootstrap.com/assets/brand/bootstrap-solid.svg" width="30" height="30"
                 class="d-inline-block align-top" alt="">
            {% if brand_name %} {{ brand_name }} {% else %}CFE eCommerce {% endif %}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
                    <a class="nav-link" href="{{ contact_url }}">Contact</a>
                </li>
                <li class="nav-item {% if request.path == product_list_url %}active{% endif %}">
                    <a class="nav-link" href="{{ product_list_url }}">Products</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item {% if request.path == register_url %}active{% endif %}">
                        <a class="nav-link" href="{{ register_url }}">Register</a>
                    </li>
                    <li class="nav-item {% if request.path == login_url %}active{% endif %}">
                        <a class="nav-link" href="{{ login_url }}">Login</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown link
                    </a>
                    <div class="dropdown-menu dropdown-menu-left" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>

            </ul>
            {% include 'search/snippets/search-form.html' %}
        </div>
    </div>
</nav>